
main: $(CONFIG_FILE)
	export GOKU_EDN_CONFIG_FILE=$(CONFIG_FILE) && goku

live: $(CONFIG_FILE)
	export GOKU_EDN_CONFIG_FILE=$(CONFIG_FILE) && goku

install:
	brew install yqrashawn/goku/goku

USER=theo
CONFIG_FILE="/Users/$(USER)/.config/karabiner/layers.edn"